name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # change this if you want full releases (with commit to repo)
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # change this if you want full releases (with commit to repo)
